### PR TITLE
Fix elements, add Dummy CSS

### LINKED ISSUE #19: Forecast - Today
As a VISITOR or USER,
when I visit a location forecast,
and I see the 'Today' section in the Overview,
I see the:
* weather description
* temperature
* high / low
and the: 
* City, State (short)
* Country
* Time
and I have links to:
* change location
* add as favorite (if logged in)

### PR DESCRIPTION
**Pull request by Kate-v2**
#### Description

* Today Forecast Details added
* CSS just to demonstrate elements -- replace later
* No tests

----
#### Issues # and Action
linked to #4 
closes #19 

----
#### TO DO / Noteworthy

* Replace CSS
* Refactor Massive HTML building function

----
#### Features
- [ ] New Feature
- [x] Expand Feature
- [ ] Optimize/Improve Feature

----
#### Testing
- [x] No Testing
- [ ] Some Testing
- [ ] Sufficient Testing

- [ ] **I have left notes near functions that have not been tested**
- [ ] **I have included intentionally skipped / failing / empty tests as a reminder to add/improve these later**

- [ ] Tests have been changed
- [ ] Existing tests are now failing / skipped

----
#### Deployment
- [x] This is a complete feature, ready for deployment
- [ ] This is a partial feature, NOT ready for deployment

----
#### API Changes
(please detail in description)
- [ ] New API
- [ ] Existing API, New Endpoint

- [ ] **I have updated the README.md**

----
#### Tech Changes
(please detail in description)
- [ ] New Functional Library
- [ ] New Testing Library
- [ ] New Debugging Tool

- [ ] **I have updated the README.md**

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -28,11 +28,83 @@ function getForecast(city = null){
...
+      let today2_3 = addDiv(today2, 'today2_3', 'today2')
+      appendText(today2_3, data['time'])
+
+    let today3 = addSpan(showToday, 'today2_location', 'today')
+      // let today3_1 = addSpan(today3, 'today3_1', 'today3')
+      let today3_1 = addDiv(today3, 'today3_1', 'today3')
+      appendText(today3_1, "Change Location")
+      let today3_2 = addDiv(today3, 'today3_2', 'today3')
+      appendText(today3_2, "Add to Favorites")
+
```
Comment (Kate-v2) [inline lib/index.js]: @corywest Hi Cory, can you review this?

First off, I hate what I'm doing here, this is a massive method and goes against everything I've learned so far, but I couldn't get require/import to work (like most of the class) and I didn't want to make methods for each of these pieces because naming and file structure started to feel cumbersome. 

Essentially, what's happening here is, I'm filling an empty div on my page with content for one of the Forecast boxes from the wire frame. I'm going to use flexbox to handle the positioning, which is why I have so many nested Divs/Spans. --- If there's a better way to do that, I haven't received feedback on that thus far and would love to hear.

Otherwise, my big questions with this method is - should I have a method that builds all these empty divs/spans before I try to fill them with another method? 

My concern is that this method gets called with from the API request, and thus only happens when the API returns. I guess, in this case, all of the content on that page (the other two forecast boxes) come from the same API, so I don't have to worry about the order of API's returning... 

But hypothetically, if I did need multiple API requests, would this HTML structure not necessarily end up being built in the section of the page I intend it for, because whichever API returned first would build first (ie append to container first)?

Comment (Kate-v2) [reply lib/index.js]: These are my flexbox & grid intentions for the two Today-related forecast boxes of the wireframe.

Comment (Kate-v2) [reply lib/index.js]: This is deployed [here](https://kate-v2.github.io/sweater_weather_web/) which should give you access to my whole index.js file if that's easier to understand than this little snip
